version: "3"

services:
  db:
    image: mysql:8
    container_name: mysql-db
    volumes:
      - dbData:/var/lib/mysql
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=dbadmin
      - MYSQL_PASSWORD=airflow
      - MYSQL_DATABASE=sakila
      - MYSQL_PORT=3306
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  app:
    build:
      context: .
    container_name: sunday-api

    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations users api &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  rdCache:
    image: redis
    container_name: sunday-caching
    restart: unless-stopped
    volumes:
      - cacheData:/data
    ports:
      - "6378:6379"
    environment:
      - LOG_LEVEL=info
volumes:
  dbData:
  cacheData:
