# Generated by Django 4.2.10 on 2024-04-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rental_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
