---
name: Checks
on: [ push ]
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-actions@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER-HUB-TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app bash -c "./run_tests.sh"
      - name: Lint
        run: docker compose run --rm app bash -c "flake8 --ignore=W191,E101,E126"
